# Use a base image that has bash and apt (e.g., ubuntu)
FROM zimbora/arduino-deploy-amd:latest

# Set a default value (optional)
ENV BASE_DIR=/root
ARG PROJECT="esp32-freeRTOS2"
ARG APP="demo"
ARG BUILD="dev"


RUN echo "APP:${APP}"

# Copy the script into the container
COPY . /${PROJECT}

# Make the script executable
RUN chmod +x /${PROJECT}/deploy.sh

# Set the working directory to your project directory
WORKDIR /${PROJECT}

RUN ./deploy.sh -d $BASE_DIR -p $PROJECT -a $APP -b $BUILD